config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :spots do
    collection do
      get 'search'
      devise_for :users
      resources :spots
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ApplicationRecord
    mount_uploader :image, ImageUploader
    enum category:{カラフル: "カラフル", 動物みくじ: "動物みくじ", 水占い: "水占い", 花手水: "花手水", 雨の日: "雨の日", 子ども: "子ども", 車椅子: "車椅子"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :root_path
    

  def after_sign_in_path_for(resource)
    spots_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     log_in user
     params[:session][:remember_me] == '1' ? remember(user) : forget(user)
     redirect_to user
   else
     flash.now[:danger] = 'Invalid email/password combination'
     render 'new'
   end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]
  # GET /spots
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  def create
    @spot = Spot.new(spot_params)

    if @spot.save
      redirect_to spots_url, notice: '作成されました'
    else
      render :new
    end
  end

  # PATCH/PUT /spots/1
  def update
    if @spot.update(spot_params)
      redirect_to spots_url, notice: '更新されました'
    else
      render :edit
    end
  end

  # DELETE /spots/1
  def destroy
    @spot.destroy
    redirect_to spots_url, notice: '削除しました'
  end
  
  def search
    @results = @q.result(distinct: true)
  end

  private

  def set_q
    @q = Spot.ransack(params[:q])
  end
    # Use callbacks to share common setup or constraints between actions.
  def set_spot
    @spot = Spot.find(params[:id])
  end

    # Only allow a trusted parameter "white list" through.
  def spot_params
    params.require(:spot).permit(:name, :comment, :address, :tel, :price, :parking, :access, :url, :category, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # 記憶トークンcookieに対応するユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def bs4_bgcolor_for(flash_key)
    case flash_key
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_key.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/home/index.html.erb
<h1 class="display-1 text-white text-center font-weight-bold" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">KYOTO</h1>
<h2 class="text-center" style="color: #ccc">京都の観光スポット</h2>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
      <%  if user_signed_in?  %>
      <% else %>
        <a class="btn btn-secondary d-block d-md-inline-block mb-2 mb-md-0" href="spots/users/sign_in" role="button">管理者用</a>
      <% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'KYOTO', root_path, class: "navbar-brand" %>
  
  <div class="btn-group">
  <!-- 切替ボタンの設定 -->
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    インスタ映え
  </button>
  <!-- ドロップメニューの設定 -->
  <div class="dropdown-menu">
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=カラフル&commit=検索">カラフル</a>
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=動物みくじ&commit=検索">動物みくじ</a>
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=水占い&commit=検索">水占い</a>
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=花手水&commit=検索">花手水</a>
  </div><!-- /.dropdown-menu -->
</div><!-- /.dropdown -->

  <div class="btn-group">
  <!-- 切替ボタンの設定 -->
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    楽しめる
  </button>
  <!-- ドロップメニューの設定 -->
  <div class="dropdown-menu">
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=雨の日&commit=検索">雨の日</a>
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=子ども&commit=検索">子ども</a>
    <a class="dropdown-item" href="https://sleepy-retreat-66493.herokuapp.com/spots/search?utf8=✓&q%5Bcategory_cont%5D=車椅子&commit=検索">車椅子</a>
  </div><!-- /.dropdown-menu -->
</div><!-- /.dropdown -->

      <%  if user_signed_in?  %>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <div class="collapse navbar-collapse" id="navbarNav">
　　<ul class="navbar-nav ml-auto">
　　　  
　　　 <li class="nav-item">
       <%= link_to "一覧",   spots_path, :class => "d-none d-lg-block btn btn-secondary rounded-pill" %>
       <%= link_to "一覧",   spots_path, :class => "d-block d-lg-none nav-link" %>
       </li>
       <li class="nav-item">
       <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => "d-none d-lg-block btn btn-outline-secondary rounded-pill" %>
       <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => "d-block d-lg-none nav-link" %>
       </li>  
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kyoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <div id="modalArea"></div>
    <main>
      <div class="container-fruid h-100 p-2 d-flex flex-column">
    <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KYOTO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KYOTO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">

        <%= yield %>
     <div class="loopSlide">
  <ul>
    <li><a href="#"><img src="https://souda-kyoto.jp/blog/ea410e0000000rlo-img/01_1.jpg" alt=""></a></li>
    <li><a href="#"><img src="https://upload.wikimedia.org/wikipedia/commons/d/d3/Kinkaku-ji_2015.JPG" alt=""></a></li>
    <li><a href="#"><img src="https://kawaii-kyoto.net/wp-content/uploads/2018/12/youkokuji7.jpg" alt=""></a></li>
    <li><a href="#"><img src="https://www.gct.co.jp/kyoto/kanko/_src/15474/img20190629222831134997.png" alt=""></a></li>
  </ul>
  <ul>
    <li><a href="#"><img src="https://souda-kyoto.jp/blog/ea410e0000000rlo-img/01_1.jpg" alt=""></a></li>
    <li><a href="#"><img src="https://upload.wikimedia.org/wikipedia/commons/d/d3/Kinkaku-ji_2015.JPG" alt=""></a></li>
    <li><a href="#"><img src="https://kawaii-kyoto.net/wp-content/uploads/2018/12/youkokuji7.jpg" alt=""></a></li>
    <li><a href="#"><img src="https://www.gct.co.jp/kyoto/kanko/_src/15474/img20190629222831134997.png" alt=""></a></li>
  </ul>
</div>
      </div>

    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/spots/_form.html.erb
<%= form_with(model: spot, local: true) do |form| %>
  <% if spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :名前 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :コメント %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :TEL %>
    <br>
    <%= form.telephone_field :tel %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :駐車場 %>
    <%= form.text_field :parking %>
  </div>

  <div class="field">
    <%= form.label :Googleマップ%>
    <%= form.text_field :access %>
  </div>

  <div class="field">
    <%= form.label :ホームページ %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :カテゴリー %>
    <%= form.select :category, Spot.categories.keys.to_a, {} %>
  </div>
  
  <div class="field">
  <%= form.label :写真をアップロード %>
  <br>
  <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h2>編集</h2>

<%= render 'form', spot: @spot %>

<%= link_to '戻る', spots_path %>

app/views/spots/index.html.erb
<p id="notice"><%= notice %></p>

<br>

<%= link_to 'New Spot', new_spot_path %>
<br>

<h2>カテゴリー検索</h2>
<%= search_form_for @q, url: search_spots_path do |f| %>
  <%= f.select :category_cont, {カラフル: "カラフル", 動物みくじ: "動物みくじ", 水占い: "水占い", 花手水: "花手水", 雨の日: "雨の日", 子ども: "子ども", 車椅子: "車椅子"} %>
  <%= f.submit '検索' %>
<% end %>
<br>

<table>
  <thead>
    <tr height="80">
      <th>写真</th>
      <th>名前</th>
      <th>コメント</th>
      <th>住所</th>
      <th>TEL</th>
      <th>料金</th>
      <th>駐車場</th>
      <th>アクセス</th>
      <th>カテゴリー</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
				<td><%= image_tag spot.image.to_s, width: 180, hight:100;%></td>
        <td width="180">
        <% if spot.url? %>
          <%= link_to spot.name, spot.url %>
        <% else %>
          <%= spot.name %>
        <% end %>
          </td>
        <td><%= spot.comment %></td>
        <td><%= spot.address %></td>
        <td width="120"><%= spot.tel %></td>
        <td><%= spot.price %></td>
        <td><%= spot.parking %></td>
        <td width="115"><%= link_to 'Google マップ', spot.access %></td>
        <td width="115"><%= spot.category %></td>
        <td><%= link_to '編集', edit_spot_path(spot) %></td>
        <td><%= link_to '削除', spot, method: :delete, data: { confirm: '本当によろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spots/new.html.erb
<h2>New Spot</h2>

<%= render 'form', spot: @spot %>

<%= link_to '戻る', spots_path %>

app/views/spots/search.html.erb
<h1><%= @results[0].category %></h1>


<table>
  <thead>
  </thead>

  <tbody>
    <% @results.each do |spot| %>
      <tr>
	　 <td width="100">
		  <br>
		  <%= image_tag spot.image.to_s, width: 250, hight:150;%>
		  <p style="text-align: center">
		  <br>
		  <% if spot.url? %>
          <%= link_to spot.name, spot.url %>
          <% else %>
          <%= spot.name %>
          <% end %>
          </p>
				</td>

        <td>
        <p class="p1"><%= spot.comment %></p>
        <p>住所：<%= spot.address %></p>
        <p>
         <% if spot.tel? %>
          TEL：<%= spot.tel %>
         <% end %>
        </p>
        <p>料金：<%= spot.price %></p>
        <p>駐車場：<%= spot.parking %></p>
        <p><%= link_to 'Google マップ', spot.access %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', root_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @spot.name %>
</p>

<p>
  <strong>コメント:</strong>
  <%= @spot.comment %>
</p>

<p>
  <strong>住所:</strong>
  <%= @spot.address %>
</p>

<p>
  <strong>TEL:</strong>
  <%= @spot.tel %>
</p>

<p>
  <strong>料金:</strong>
  <%= @spot.price %>
</p>

<p>
  <strong>駐車場:</strong>
  <%= @spot.parking %>
</p>

<p>
  <strong>Googleマップ:</strong>
  <%= @spot.access %>
</p>

<p>
  <strong>ホームページ:</strong>
  <%= @spot.url %>
</p>

<p>
  <strong>カテゴリー:</strong>
  <%= @spot.category %>
</p>

<% if @spot.image? %>
  <p>
    <strong></strong>
    <%= image_tag @spot.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
  </p>
<% end %>

<%= link_to '編集', edit_spot_path(@spot) %> |
<%= link_to '戻る', spots_path %>